.version
.database
.show
.tables

DROP TABLE IF EXISTS CA_USERS;
CREATE TABLE IF NOT EXISTS CA_USERS
(
    CA_ID  STRING ,
    CA_PSWRD STRING
);

INSERT INTO CA_USERS (CA_ID, CA_PSWRD) VALUES ("carlos.aleman@epn.edu.ec","1751424324");
INSERT INTO CA_USERS (CA_ID, CA_PSWRD) VALUES ("joel.altamirano@epn.edu.ec","1754944336");
INSERT INTO CA_USERS (CA_ID, CA_PSWRD) VALUES ("profe","1234");
SELECT * FROM CA_USERS;
DROP TABLE IF EXISTS CA_COORDS;
CREATE TABLE IF NOT EXISTS CA_COORDS
(
    CA_CAP  INT ,
    CA_GEO STRING,
    CA_ARS STRING,
    CA_FECHA STRING DEFAULT(datetime('now'))
);


INSERT INTO CA_COORDS (CA_CAP, CA_GEO, CA_ARS) VALUES (4,"GPS4","acd");
INSERT INTO CA_COORDS (CA_CAP, CA_GEO, CA_ARS) VALUES (2,"GPS2","ac");
INSERT INTO CA_COORDS (CA_CAP, CA_GEO, CA_ARS) VALUES (3,"GPS3","bcd");
INSERT INTO CA_COORDS (CA_CAP, CA_GEO, CA_ARS) VALUES (4,"GPS4","acd");
INSERT INTO CA_COORDS (CA_CAP, CA_GEO, CA_ARS) VALUES (2,"GPS2","ac");
INSERT INTO CA_COORDS (CA_CAP, CA_GEO, CA_ARS) VALUES (4,"GPS4","acd");
INSERT INTO CA_COORDS (CA_CAP, CA_GEO, CA_ARS) VALUES (1,"GPS1","bc");
INSERT INTO CA_COORDS (CA_CAP, CA_GEO, CA_ARS) VALUES (5,"GPS5","bct");
INSERT INTO CA_COORDS (CA_CAP, CA_GEO, CA_ARS) VALUES (7,"GPS7","aaabbct");
INSERT INTO CA_COORDS (CA_CAP, CA_GEO, CA_ARS) VALUES (1,"GPS1","bc");
SELECT * FROM CA_COORDS;

DROP TABLE IF EXISTS JA_COORDS;
CREATE TABLE IF NOT EXISTS JA_COORDS
(
    JA_CAP  INT ,
    JA_GEO STRING,
    JA_ARS STRING,
    JA_FECHA STRING DEFAULT(datetime('now'))
);
INSERT INTO JA_COORDS (JA_CAP, JA_GEO, JA_ARS) VALUES (6,"GPS6","act");
INSERT INTO JA_COORDS (JA_CAP, JA_GEO, JA_ARS) VALUES (3,"GPS3","bcd");
INSERT INTO JA_COORDS (JA_CAP, JA_GEO, JA_ARS) VALUES (3,"GPS3","bcd");
INSERT INTO JA_COORDS (JA_CAP, JA_GEO, JA_ARS) VALUES (4,"GPS4","acd");
INSERT INTO JA_COORDS (JA_CAP, JA_GEO, JA_ARS) VALUES (4,"GPS4","acd");
INSERT INTO JA_COORDS (JA_CAP, JA_GEO, JA_ARS) VALUES (9,"GPS9","aaabbcd");
INSERT INTO JA_COORDS (JA_CAP, JA_GEO, JA_ARS) VALUES (4,"GPS4","acd");
INSERT INTO JA_COORDS (JA_CAP, JA_GEO, JA_ARS) VALUES (5,"GPS5","bct");
INSERT INTO JA_COORDS (JA_CAP, JA_GEO, JA_ARS) VALUES (7,"GPS7","aaabbct");
INSERT INTO JA_COORDS (JA_CAP, JA_GEO, JA_ARS) VALUES (1,"GPS1","bc");
SELECT * FROM JA_COORDS;

DROP TABLE IF EXISTS PF_COORDS;
CREATE TABLE IF NOT EXISTS PF_COORDS
(
    PF_CAP  INT ,
    PF_GEO STRING,
    PF_ARS STRING,
    PF_FECHA STRING DEFAULT(datetime('now'))
);
INSERT INTO PF_COORDS (PF_CAP, PF_GEO, PF_ARS) VALUES (4,"GPS4","acd");
INSERT INTO PF_COORDS (PF_CAP, PF_GEO, PF_ARS) VALUES (3,"GPS3","bcd");
INSERT INTO PF_COORDS (PF_CAP, PF_GEO, PF_ARS) VALUES (2,"GPS2","ac");
INSERT INTO PF_COORDS (PF_CAP, PF_GEO, PF_ARS) VALUES (1,"GPS1","bc");
SELECT * FROM PF_COORDS;